#version: '3'  # condition недоступна в версии 3
version: '2.3'
services:
  postgresql:
    image: postgres:13
    env_file: ./app/config/.env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    networks:
      - my-network
    ports:
      - "5432:5432"

  service:  # django
    build: app
    env_file: ./app/config/.env
    networks:
      - my-network
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    networks:
      - my-network
    volumes:
      - ./app/static:/opt/app/static:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    restart: always
    ports:
      - "80:80"

  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms500m -Xmx500m'
    networks:
      - my-network
    ports:
      - '9200:9200'
    depends_on:
      - service
      - postgresql
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5

  etl:
    build: etl
    env_file: ./etl/.env
    networks:
      - my-network
    restart: always
    depends_on:
      elastic_search:
        condition: service_healthy

networks:
  my-network:
    external: true
